name: CI

on:
  push:
    branches:
      - "**"

jobs:
  example:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - run: bazelisk build ...
        working-directory: example
